config/routes.rb
Pmtool::Application.routes.draw do
  resources :proposals

end

app/models/proposal.rb
require 'savon'

class Proposal < ActiveRecord::Base

	include ActiveModel::Dirty

	before_create :assign_rmas_id
	after_save :rmas_event
	after_destroy :rmas_destroy

	before_save do
		@changed_fields = self.changed
	end

	def generate_rmas_id
		# generate a new rmas id
		"urn:rmas:kent:pmtool:#{SecureRandom.uuid}"
	end

	def assign_rmas_id
		self.rmas_id = generate_rmas_id()
		@new_rec = true
	end

	def rmas_event
		if @new_rec
			self.rmas_new
		else
			self.rmas_updated
		end
	end

	def rmas_new
		puts 'sending proposal_created message'

		# generate the message
		message = {
			:message_type => 'proposal_created',
			:entity => {
				:id => self.rmas_id,
				:title => self.title,
				:description => self.description
			}
		}

		send_message message

	end

	def rmas_updated
		
		puts 'sending proposal_updated message'

		message = {
			:message_type => 'proposal_updated',
			:entity => {
				:id => self.rmas_id
			}
		}

		unless @changed_fields.empty?
			@changed_fields.each do |field|
				message[:entity].store(field, self[field])
			end
			
			puts message

			send_message message
		end
	end

	def rmas_destroy
		puts 'sending proposal_deleted message'

		message = {
			:message_type => 'proposal_deleted',
			:entity => {
				:id => self.rmas_id
			}
		}

		send_message message
	end

	def send_message(message)

		client = Savon::Client.new do
			wsdl.document = 'http://129.12.9.208:6980/EventService?wsdl'
		end

		message['message_id'] = generate_rmas_id()

		message_json = ActiveSupport::JSON.encode(message)

		response = client.request :push_event do
			soap.body = { :message => message_json }
		end

		unless response.success?
			puts response.soap_fault
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Proposal Management Tool</title>
	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class='topbar'>
		<div class='fill'>
			<div class='container'>
				<a class='brand' href='/proposals'>Proposal Management Tool</a>
			</div>
		</div>
	</div>
	<div class='container'>
		<div class='content'>
			<%= yield %>
		</div>
		<footer>
			<p>University of Kent</p>
		</footer>
	</div>

</body>
</html>

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
	<% if @proposal.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

			<ul>
			<% @proposal.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="clearfix">
		<%= f.label :title %>
		<div class='input'>
			<%= f.text_field :title, :class => 'xlarge' %>
		</div>
	</div>
	<div class="clearfix">
		<%= f.label :description %>
		<div class='input'>
			<%= f.text_area :description, :class => 'xxlarge', :rows => 6 %>
		</div>
	</div>
	<div class="actions">
		<%= f.submit :class => 'btn primary' %>
	</div>
<% end %>

app/views/proposals/edit.html.erb
<div class='page-header'>
  <h1>Editing proposal</h1>
</div>

<div class='row'>
  <div class='span14'>
	<%= render 'form' %>

	<%= link_to 'Show', @proposal, :class => 'btn' %>
	<%= link_to 'Back', proposals_path, :class => 'btn' %>
  </div>
</div>

app/views/proposals/index.html.erb
<div class='page-header'>
  <h1>Proposals</h1>
</div>

<div class='row'>
  <div class='span14'>
    <table class='zebra-striped'>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th style='width: 10%'></th>
        <th style='width: 10%'></th>
      </tr>

    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= link_to proposal.title, proposal %></td>
        <td><%= truncate proposal.description, :length => 60, :separator => ' ' %></td>
        <td><%= link_to 'Edit', edit_proposal_path(proposal), :class => 'btn' %></td>
        <td><%= link_to 'Delete', proposal, confirm: 'Are you sure?', method: :delete, :class => 'btn danger' %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Proposal', new_proposal_path, :class => 'btn primary' %>
  </div>
</div>

app/views/proposals/new.html.erb
<div class='page-header'>
  <h1>New proposal</h1>
</div>

<div class='row'>
  <div class='span14'>
	<%= render 'form' %>

	<%= link_to 'Back', proposals_path, :class => 'btn' %>
  </div>
</div>

app/views/proposals/show.html.erb
<div class='page-header'>
  <h1><%= @proposal.title %></h1>
</div>

<div class='row'>
  <div class='span14'>

  	<% if notice then %>
	<div class='alert-message success'>
		<a class='close' href='#'>x</a>
		<p><%= notice %></p>
	</div>
	<% end %>

	<%= simple_format @proposal.description %>

	<div class='well show-well'>
		<strong>RMAS ID:</strong> <code><%= @proposal.rmas_id %></code>
	</div>

	<div class='links'>
		<%= link_to 'Edit', edit_proposal_path(@proposal), :class => 'btn' %>
		<%= link_to 'Back', proposals_path, :class => 'btn' %>
	</div>
  </div>
</div>